### ISSUE TITLE
a new idea

### ISSUE THREAD

**Issue by yuanf225** [AnchyDev/HardMode#1]
1、respawn mode
2、Characters who have reached the level cap can receive a rebirth quest from npc, submit them to get rewards such as set currency/items, and at the same time return the character level to level 1, and remove all spells and talents

**Comment by AnchyDev** [comment]
You can implement this yourself by rewarding the player with an item that starts the rebirth quest. I likely won't implement this as a feature as it's not really relevant to the hardmode module.

The module is also having a large re-write at the moment so I am focusing on implementing the basics again.
