### ISSUE TITLE
Suggestions on some issues

### ISSUE THREAD

**Issue by 1825679767** [AnchyDev/HardMode#7]
I want to consult the configuration of hard mode. Players can switch hard mode on and off freely. If I set the level to 80 to give rewards, can players normally play to level 79 and then turn on hard mode?

In addition, what are the types of reward_type?

**Comment by AnchyDev** [comment]
If you "taint" your character you cannot enable modes.

Tainting happens when you:
- Gain experience
- Use the mailbox
- Trade another player
and a few other requirements.

These are the reward types:
https://github.com/AnchyDev/HardMode/blob/master/src/HardModeTypes.h#L64
