### ISSUE TITLE
Fresh characters starting tainted, shadowbanned or undertaking challenge

### ISSUE THREAD

**Issue by Auz-kiee** [AnchyDev/HardMode#9]
I figured out that Acore_characters.hardmode_player_settings table entries don't automatically clear if a character is deleted.
So when a character with an entry in this table is eventually deleted by player or otherwise, if a totally different player makes a new character they may be assigned the lowest unused GUID resulting in new characters starting possibly tainted, undertaking a challenge or even in the shadowrealm. It's happened multiple times for me so far.

Is the simplest fix adding a foreign key constraint with cascading deletes?
Something like:
ALTER TABLE hardmode_player_settings
ADD CONSTRAINT fk_guid
FOREIGN KEY (guid) REFERENCES characters(guid)
ON DELETE CASCADE;

Keen to hear your thoughts on this, cheers mate
-Auzkiee

**Comment by AnchyDev** [comment]
Should be solved by latest commit.
